# version: "3.8"

networks:
  gitea:
    external: false

services:
  gitea:
    image: docker.gitea.com/gitea:1.24.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://host.docker.internal:3000
    restart: always
    networks:
      - gitea
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitea-runner
    environment:
      GITEA_INSTANCE_URL: "http://host.docker.internal:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "L1wPrq9d4r7Q3srnULedPArVqNs0w1uFiuaNb27S"
      GITEA_RUNNER_NAME: "runner01"
    depends_on:
      gitea:
        condition: service_healthy
    networks:
      - gitea
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./runner:/data
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "/scripts/runner-entrypoint.sh"]
