version: "3.8"

networks:
  gitea:
    external: false

services:
  gitea:
    image: docker.gitea.com/gitea:1.24.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  runner:
    image: docker.io/gitea/act_runner:latest
    environment:
      GITEA_INSTANCE_URL: "http://gitea:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "L1wPrq9d4r7Q3srnULedPArVqNs0w1uFiuaNb27S"
      GITEA_RUNNER_NAME: "runner01"
    networks:
      - gitea
    depends_on:
      gitea:
        condition: service_healthy
    volumes:
      - ./runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
